{"uuid": "0fbe37a6-ba30-408d-889d-ebffcf0e2ed1", "children": ["7936c3fe-227a-4bf1-8fbd-211a4f50fd02"], "befores": [{"name": "setup_AvecConnexionUser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed\n  (Session info: chrome=99.0.4844.84)\nStacktrace:\n0   chromedriver                        0x00000001053b3960 chromedriver + 4438368\n1   chromedriver                        0x000000010534903c chromedriver + 4001852\n2   chromedriver                        0x0000000104f9e30c chromedriver + 156428\n3   chromedriver                        0x0000000104f8fae4 chromedriver + 96996\n4   chromedriver                        0x0000000104f8a514 chromedriver + 75028\n5   chromedriver                        0x0000000104ff5c58 chromedriver + 515160\n6   chromedriver                        0x0000000104fc2400 chromedriver + 304128\n7   chromedriver                        0x00000001053764a8 chromedriver + 4187304\n8   chromedriver                        0x000000010538c588 chromedriver + 4277640\n9   chromedriver                        0x0000000105391268 chromedriver + 4297320\n10  chromedriver                        0x000000010538cdd0 chromedriver + 4279760\n11  chromedriver                        0x000000010536c2ec chromedriver + 4145900\n12  chromedriver                        0x00000001053a5f0c chromedriver + 4382476\n13  chromedriver                        0x00000001053a6080 chromedriver + 4382848\n14  chromedriver                        0x00000001053ba28c chromedriver + 4465292\n15  libsystem_pthread.dylib             0x00000001856fe26c _pthread_start + 148\n16  libsystem_pthread.dylib             0x00000001856f908c thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/TestCases/conftest.py\", line 43, in setup_AvecConnexionUser\n    hp.clickaccepterTCF()\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/PageObjects/HomePage.py\", line 27, in clickaccepterTCF\n    self.obj.click(Locators.accepter_btnTCF_CSS)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/PageObjects/common_Actions.py\", line 33, in click\n    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(by_locator)).click()\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 78, in until\n    value = method(self._driver)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/support/expected_conditions.py\", line 125, in _predicate\n    return _element_if_visible(driver.find_element(*locator))\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1244, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1648726125755, "stop": 1648726129041}], "start": 1648726125755, "stop": 1648726129125}