{"uuid": "0cdf3dc4-96ae-4e75-8f51-bbc7f11445d4", "children": ["a06b3f2f-3a95-4402-a3c4-9171b43d9579"], "befores": [{"name": "setup_AvecConnexionUser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"email\"]\"}\n  (Session info: chrome=99.0.4844.74)\nStacktrace:\n0   chromedriver                        0x000000010052f960 chromedriver + 4438368\n1   chromedriver                        0x00000001004c503c chromedriver + 4001852\n2   chromedriver                        0x000000010011a30c chromedriver + 156428\n3   chromedriver                        0x000000010014923c chromedriver + 348732\n4   chromedriver                        0x0000000100172454 chromedriver + 517204\n5   chromedriver                        0x000000010013e400 chromedriver + 304128\n6   chromedriver                        0x00000001004f24a8 chromedriver + 4187304\n7   chromedriver                        0x0000000100508588 chromedriver + 4277640\n8   chromedriver                        0x000000010050d268 chromedriver + 4297320\n9   chromedriver                        0x0000000100508dd0 chromedriver + 4279760\n10  chromedriver                        0x00000001004e82ec chromedriver + 4145900\n11  chromedriver                        0x0000000100521f0c chromedriver + 4382476\n12  chromedriver                        0x0000000100522080 chromedriver + 4382848\n13  chromedriver                        0x000000010053628c chromedriver + 4465292\n14  libsystem_pthread.dylib             0x00000001b64614ec _pthread_start + 148\n15  libsystem_pthread.dylib             0x00000001b645c2d0 thread_start + 8\n\n", "trace": "  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/TestCases/conftest.py\", line 44, in setup_AvecConnexionUser\n    lp.setUsername(username)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/PageObjects/ObPage.py\", line 17, in setUsername\n    self.driver.find_element(By.ID,Locators.textbox_username_id).clear\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1248, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1647937811766, "stop": 1647937821028}], "start": 1647937811766, "stop": 1647937821109}